### ISSUE TITLE
Find a better way to mark all dependencies as externals

### ISSUE THREAD

**Issue by jayair** [serverless-stack/serverless-stack#102]
Right now, we use esbuild to mark the CDK and Lambda code's dependencies as externals by looking at the `package.json`. But for some setups, where the dependencies are not listed (nested `package.json` files), this doesn't work. Two options to investigate:

- Does the [esbuild external `*`](https://esbuild.github.io/api/#external) option work
- Use [a plugin to mark them all as externals](https://github.com/evanw/esbuild/issues/619#issuecomment-751995294)

**Comment by olup** [comment]
Can I add that for many setups you actually don't want to externalize all your deps, because many CAN be bundled, and that could save a lot of space ! It's imperative (and I'd say high prio) to let user decide the list of externals they want to bundle. Actually, every esbuild options should be editable, the way we do it in serverless-esbuild, with sane defaults, don't you think ?

**Comment by thdxr** [comment]
I'm not sure if this is relevant anymore since we have support for specify what you want to be external vs bundled.  Closing for now
