### ISSUE TITLE
Why is everyone operating in this space intent on making blackboxes?

### ISSUE THREAD

**Issue by AshHeskes** [serverless-stack/serverless-stack#1038]
I like the tool it seems to work fine, but it is just so annoying you don't provide documentation on the actual hard parts.

1. What does `npx sst build` do. Why are there so many outputs that seem to be the same thing just slightly different?
2. You bundle esbuild, how do I configure esbuild, What if I want my own CI/CD and to use artefacts, how do I deploy them.
3. All your examples create a `package.json` full of dependencies that any sane developer would consider dev dependencies (nobody is using your CLI in code) why?
4. You talk about monorepos on your FAQ yet it seems by default you adopt a sort of monorepo structure with nested folders in src having their own `package.json`.
5. What does the eslint plugin actually lint?
6. What about when I want to define build test and lint commands in different envs?

I mean great work on creating a dev tool that seems to best all others in the space. But at the same time don't fall down the same trap of blackboxing everything. I literally just started using it and it's great for a demo, but I cannot for the life of me figure out how I would use this in production.

Lastly please stop with the `npx sst deploy <stage>` it doesn't happen in any real-world situation. I want to know how deploys work and I don't want my developers to access to any stage other than local from a CLI (it's just mental any other way so why provide it).

**Comment by AshHeskes** [comment]
Just to add... I would love to hear what `env.prod.local` for example would actually be expected to do? By definition, it is local but also prod? What does that even mean?

**Comment by jayair** [comment]
Hey @AshHeskes I'll let @fwang or @thdxr chime in on some of the details here. But I appreciate you bringing this up. Some of our docs assume prior knowledge of the systems we are using internally. So your questions can help us figure out what we need to document better.

Also, we don't want to be building a "blackbox" system.

I'm curious about this though:

> Lastly please stop with the npx sst deploy <stage> it doesn't happen in any real-world situation

It's used in [Serverless Framework](https://github.com/serverless/serverless) and all our customers use it to configure their CI/CD pipelines on [Seed](https://seed.run) as well. How do you configure your pipelines to deploy to different environments currently?

Oh and for the `env.prod.local`, you might've noticed the docs on it: https://docs.serverless-stack.com/environment-variables. It uses the same convention as Create React App or Next.js. Admittedly the naming is confusing but it's something a lot folks are familiar with.

**Comment by AshHeskes** [comment]
So the problem with `npx sst deploy <stage>` is that it is a black box. My developers are never going to run this command, and no developers ever should. Just as a matter of course for security and standards. But I have no idea what it does... I can of course not give my devs access to any credentials that would allow them to use it. Which would be the default for any organisation... So why not just explain both:

a) What it does.
b) How you do it without it (which ironically explains what it does). 

And stop referring to it in docs as it's as easy as `npx sst deploy`. It never is and it's just frustrating to keep seeing it without any reference docs.

**Comment by AshHeskes** [comment]
In regards to what is available in serverless framework, I wouldn't mimic it. One of the reasons we started looking at SST is because we were using Serveless Framework. Again their documentation was terrible, beyond terrible in fact. We didn't want to confine ourselves to AWS (initially) but in reality, it is unavoidable and local dev is a pain. So we really like your solution for local dev. 

In short I would not mimic Serverless framework to any degree, it is just terrible for anything even slightly outside of basic functions. They have the same blackbox `serverless deploy`... I want control over what is built and what is deployed and how. I like the idea of AWS CDK for the infra as code. I just don't understand since you are doing that why not just focus on the pains of local dev, rather than deploys. You are making deploys harder than they should be at least from what I gather.  For anything other than basic functions.

Solve local dev, give full flexibility over linting, testing, CI/CD. It is just not obvious how this is not baked in and you either use it as or suck a lemon.

**Comment by AshHeskes** [comment]
It would be great for once if there was a solution that solves for local dev (which yours seems to do) but not any other env, and even in local dev everything just works from standard dev practices. You need my code built into a dir that your framework uses for the other hard work, fine. Let me tell you where I'm outputting it. I do not need your framework choosing how I build my services, lint them, test them or anything else. 

It is too complex to detail everything here and how I might perhaps go about it. So maybe let's find a way to take this to another more conversational forum if you are happy with that?

**Comment by thdxr** [comment]
Hey Ash - I've actually been working to make a lot of the issues less of a blackbox and behave in a more standard way. Definitely agree we need to be playing nicer with some of the dependencies we use (cdk, esbuild, etc).  I also personally align with you a bit in that I want SST doing less out of the box and we are actually in the minority.  I'll answer your questions with some of my personal choices.

> What does npx sst build do. Why are there so many outputs that seem to be the same thing just slightly different?

The reason for all the outputs is CDK automatically adds extra stuff for cross stack dependencies. We have a PR open that hides those automatic ones because 99% of the time they aren't useful.

This commands builds all of your stacks currently to a `.build` folder - I'm working on unifying this in all the places that have that folder hard coded so that a flag can be passed in to specify that output so you can put it somewhere and have you CI archive it as an artifact. I'm assuming you want to do this for fast rollbacks - pretty cool idea.

> You bundle esbuild, how do I configure esbuild, What if I want my own CI/CD and to use artefacts, how do I deploy them.

Artifact question answered above. For configuring esbuild as documented here we allow setting some options: https://docs.serverless-stack.com/constructs/Function#esbuildconfig - you can set these as defaults or per function

> All your examples create a package.json full of dependencies that any sane developer would consider dev dependencies (nobody is using your CLI in code) why?

I personally put these things in devDependencies but if using a monorepo some people argue it makes sense as a normal dependency in the root package. I think this is more of an issue with the lack of obvious clarity around how devDependenceis and dependencies are actually used. I think from a practical perspective it makes little difference.

> You talk about monorepos on your FAQ yet it seems by default you adopt a sort of monorepo structure with nested folders in src having their own package.json.

This is actually what a monorepo is in the nodejs world. It's a single VCS repo even though there are multiple packages inside of it.  Here is a link to my personal setup: https://github.com/serverless-stack/serverless-stack/tree/master/examples/typescript-monorepo - I document some of the reasons why people prefer discrete subpackages although I personally do not use them.

> What does the eslint plugin actually lint?

It will lint both your stack code and any function code.  You can disable this in `sst.json` - I personally do this as well. I recently reworked our implementation so it behaves in a more standard way (ala create react app) and is less of a blackbox.
https://docs.serverless-stack.com/working-locally#linting--type-checking

> What about when I want to define build test and lint commands in different envs?

I personally do not use the built in testing or linting and you can see in my monorepo that I configure jest directly. In terms of different envs there's various ways to do this depending on your setup and it's hard to answer this generically.

> Lastly please stop with the npx sst deploy <stage> it doesn't happen in any real-world situation

I don't think this is correct. A "stage" is just a unit that allows you to duplicate your environment. People's personal dev environments are also stages and sometimes you want to do `sst deploy` on it. Sometimes you want to have manual deployments because your CI/CD isn't setup for a simple side project.  And even in CI I'm not sure how you would deploy without us exposing a way to deploy in the CLI

While you may disagree with the way people have things setup I ask for some respect as we see many companies and many setups (starting fresh, migrating a non serverless app, migrating serverless framework, etc) and are balancing a lot of different tradeoffs.

You may feel it is simple just to solve local dev without touching anything with how CDK deploys the reality is that's easier said than done. At one point SST had to fully fork CDK to support what we needed to do and we slowly were able to build ways around it. Some of the things you complained about are coming from CDK and we have to be fairly invasive with it to fix certain behavior.

We are still on this journey and can assure you we're thinking about this every day. Outside of the CDK team themselves we're probably the most familiar with its inner workings - consider that things are maybe more complicated than you perceive them.

**Comment by AshHeskes** [comment]
@jayair Thanks for your responses here. Firstly perhaps I was not being clear in my angst against `sst deploy > magic`. It is not that I don't see it as being useful or question that there's a lot of utility in it. It was more the frustration of the docs using it as a catchall and no clear explanation of what it is doing.

In regards to what your linting does I was more specifically referring to what the linting plugin actually does in terms of which eslint config is it using by default. e.g. eslint recommended or airbnb etc.

It sounds like a lot of the things in use are not ways you yourselves like to do it. Which seems a tad unusual, the way you have explained how you use it seems to fit the way I would want to use it. 

I think it would just be nice to have clearer explanations of how to use it in this manner in the examples and guides over going with the built-ins. Or perhaps default to this way and add convenience for people who want to use it in other ways.

You have answered most of the questions which I really appreciate and look forward to seeing how it progresses :)

**Comment by jayair** [comment]
Yeah that makes sense. A couple of takeaways:

- I think we could update this doc with a better explanation of the `sst build` and `sst deploy` commands: https://docs.serverless-stack.com/packages/cli
- And this doc could explain what the default lint config is: https://docs.serverless-stack.com/working-locally#linting--type-checking

/cc @fwang @thdxr

**Comment by AshHeskes** [comment]
I know this issue is closed, but personally, I would go further than these changes. My frustration was borne by reading your guides. Not specific CLI commands. I didn't even reach that depth.

Honestly just do this in the way you guys use it. It's the convention Vs configuration argument. Go with convention and enforce high standards through convention with explanations as to why. 

Your internal reasons for not using this tool in the way any of the docs explain say it all. In real-world situations, it's not a good convention. It might be fast at MVP. However, It seems you are listening too much to the MVP case and not enough to the production case. Which as already stated seems to be your preferred method of using it internally anyway.

**Comment by jayair** [comment]
Yeah that's fair.

@fwang for the new guide that we are working on, maybe we need to focus a bit on the production best practices as well?
