### ISSUE TITLE
ESM issues in Jest test since 1.0

### ISSUE THREAD

**Issue by hermanbanken** [serverless-stack/serverless-stack#1752]
We were using SST 0.59 before and switched to 1.29. First we needed to configure Jest, so I took a look at the old configuration that was part of SST before. Ending up with a config like this:

```javascript
  "jest": {
    "roots": [
      "<rootDir>"
    ],
    "moduleNameMapper": {
      "^src/(.*)": "<rootDir>/src/$1",
      "@ppconfig/(.*)": "<rootDir>/config/$1",
      "@ppconfig": "<rootDir>/config/index.ts"
    },
    "reporters": [
      "default",
      "github-actions"
    ],
    "testEnvironment": "node",
    "testMatch": [
      "<rootDir>/**/__tests__/**/*.{js,jsx,ts,tsx}",
      "<rootDir>/**/*.{spec,test}.{js,jsx,ts,tsx}"
    ],
    "transform": {
      "\\.ts$": "esbuild-runner/jest",
      "\\.js$": "esbuild-runner/jest"
    },
    "transformIgnorePatterns": [
      "[/\\\\]node_modules[/\\\\].+\\.(js|jsx|ts|tsx)$"
    ]
  }
```

This causes the following error:
```
 FAIL  test/ApiStack.test.ts
  ● Test suite failed to run

    Cannot find module '@serverless-stack/resources' from 'stacks/api/index.ts'

    Require stack:
      stacks/api/index.ts
      test/ApiStack.test.ts

      1 | /* eslint-disable @typescript-eslint/no-non-null-assertion */
    > 2 | import {Api, Stack, Function as SSTFunction} from '@serverless-stack/resources';
```

By adding to the moduleNameMapper object, it gets a little further:
```
      "@serverless-stack/resources": "<rootDir>/node_modules/@serverless-stack/resources",
```

Unfortunately, now the tests can't deal with the ESM codebase that sst now is:

```
    Details:

    node_modules/@serverless-stack/resources/dist/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export * from "./App.js";
                                                                                      ^^^^^^

    SyntaxError: Unexpected token 'export'

      1 | /* eslint-disable @typescript-eslint/no-non-null-assertion */
    > 2 | import {Api, Stack, Function as SSTFunction} from '@serverless-stack/resources';
        |                                                  
```

I have no idea how to solve this hell, and this tweet feels appropriate:
https://twitter.com/kentcdodds/status/1369803853005209602

**Comment by christiankaindl** [comment]
I had the same issue and wound up replacing Jest with Vitest. Vitest is API compatible with Jest, is faster and worked out-of-the box for me. It is also used in the official SST starter, which I recommend copying from.

Run:
```sh
npx create-sst@latest typescript-starter
```

From the newly created project copy over `vitest.config.ts` to your existing one, and update the "test" script to use Vitest:
```json
{
  "name": "sst-temp",
  "...": "...",
  "scripts": {
    "test": "vitest run"
  },
  "...": "...",
}
```

Lastly, add the following packages to your `devDependencies` in package.json:
```
"typescript": "^4.7.3",
"vitest": "^0.13.1"
```

---

### Additional steps
Two things that you may want to do is:
1. Vitest, by default, needs you to import the testing function (`expect()`, `test()`, etc.). In order to avoid that you need to set `globals: true` in vitest.config.ts, as well as add "vitest/globals" to your tsconfig.json (if you use TypeScript). [Docs here](https://vitest.dev/config/#globals)
2. Vitest is based on Vite, which doesn't use process.env for environment variables. This is easily solved by using "[vite-plugin-environment](https://github.com/ElMassimo/vite-plugin-environment)" which was easy to set up.

So my vitest.config.ts file with the two changes from above looks like the following:
```ts
/// <reference types="vitest" />

import { defineConfig } from "vitest/config";
import EnvironmentPlugin from 'vite-plugin-environment'

export default defineConfig({
  test: {
    testTimeout: 30000,
    globals: true
  },
  plugins: [
    EnvironmentPlugin([
      'MY_ENV_VAR', // Any env var names you want to be read from a local ".env" file
    ])
  ]
});

```

Related: https://github.com/serverless-stack/serverless-stack/issues/1722

**Comment by christiankaindl** [comment]
If you can't replace Jest, then you could try running the test script with the flag `--experimental-vm-modules` (more [here](https://jestjs.io/docs/ecmascript-modules)):
```json
{
  "scripts": {
    "test": "NODE_OPTIONS=--experimental-vm-modules jest"
  }
}
```

**Comment by fwang** [comment]
@christiankaindl thanks for sharing! That's really useful.

@hermanbanken did you manage to get it to work?

I second @christiankaindl on vitest. As a side note, we moved over to using vitest for SST internally. Tests now run much faster! Strongly recommend.

**Comment by hermanbanken** [comment]
I switched too and it works. I'm not buying into the hype completely. Vitest is indeed faster locally, but on CI/CD it is slower for us. Probably doing a lot in parallel locally that it doesn't do if `CI=1`.

**Comment by christiankaindl** [comment]
@fwang is this something that should be put in the docs? If so, would you welcome a pull request?
