### ISSUE TITLE
Services/APIs hang when using sst start

### ISSUE THREAD

**Issue by nabeelvalley** [serverless-stack/serverless-stack#341]
I'm working through the documentation and am having issues with `sst start`

I'm going through [this documentation page](https://serverless-stack.com/examples/how-to-create-a-crud-api-with-serverless-using-dynamodb.html) and when I use `sst start` the deploy seems to succeed as per CloudFormation, but when trying to make requests to the endpoints I just get a `503`:

```json
{
    "message": "Service Unavailable"
}
```

Note that the application was working previously - this issue started suddenly and I am unable to get it working again in development mode (I've even used `sst remove` and then `sst start` again)

Also, the application works fine when I use `sst deploy`, I can access it as expected

**Comment by nabeelvalley** [comment]
Got it working now, deleted resources again and spun it back up - not sure what made the difference

**Comment by jayair** [comment]
Wonder if AWS had an outage.

**Comment by nabeelvalley** [comment]
Seemed to be something with a websocket connection I think, possibly a deploy that broke, don't think it was an outage though

**Comment by AlessandroVol23** [comment]
I do have the same behaviour. 
I moved the exact same code to a monorepo and in `sst start` I do get sometimes `Service Unavailable` and sometimes it is working out. Only in the debug mode and not in a properly deployed one. 

Did anyone else face this?

**Comment by joshstrange** [comment]
@AlessandroVol23 I'm seeing this as well. It appears that if I kick of like 4+ requests at the same time to my API that 1-2+ of them will timeout and throw the `Service Unavailable` message.

I remember seeing something similar back when I used Serverless Framework + Offline mode. I know Live Lambdas are a different beast than Offline (and better in almost every way) but I'm wondering if there is some kind of limit/issue with too many requests at the same time. I hope there is fix for this since it ruin the dev environment if randomly requests fail, especially since on page load I do a number of requests to various "resource" endpoints make sure my app is fully up-to-date.
