### ISSUE TITLE
Moving from base Routes to `addRoutes` fails to deploy

### ISSUE THREAD

**Issue by justindra** [serverless-stack/serverless-stack#513]
When we move a route that was initially defined in the constructor props into the `addRoutes` method, `sst deploy` fails. Even though it is the same configuration.

```typescript
    // Initial config
    const api = new sst.Api(this, 'Api', {
      routes: {
        'GET /': 'src/lambda.handler',
        'GET /test': 'src/lambda.handlerEvent',
      },
    });

    // New config
    const api = new sst.Api(this, 'Api', {
      routes: {
        'GET /': 'src/lambda.handler',
      },
    });

    api.addRoutes(this, {
      'GET /test': 'src/lambda.handlerEvent',
    });
```

Error message (w/ IDs removed)
```
my-stack | CREATE_FAILED | AWS::ApiGatewayV2::Route | RouteGETtest... Route with key GET /test already exists for this API (Service: AmazonApiGatewayV2; Status Code: 409; Error Code: ConflictException; Request ID: ...; Proxy: null)
```

Since it is the same configuration it really should not be an issue. The workaround is currently to:
* Remove the endpoint completely
* Deploy
* Add the endpoint back in with the new config
* Deploy

Ideally it would just work as expected.

**Comment by fwang** [comment]
Hey @justindra, thanks for bringing this up! Unfortunately this is the expected behaviour given how CDK generates the ids (CloudFormation Logical IDs) for the routes.

When defined through the constructor, the Logical ID for the `GET /test` route looks like `ApiRouteGETtestXXXXXXXX`. But if added via the `addRoutes` call, the Logical ID looks like `RouteGETtestXXXXXXXX`. This is because in the former case, the route is a child of the `sst.Api` construct, so CDK prefixes its Logical ID with the construct name `Api`. Whereas in the latter case, the route is a child of the stack directly, hence not prefixed with `Api`. And when the ID for a resource change, CloudFormation tries to recreate it.

As a side note, the `addRoutes()` function is mostly used to add routes across stacks (ie. `sst.Api` created in stackA, and `addRoutes` called in stackB). If a route (ie. /test) is "moved" from stackA to stackB, CloudFormation would deploy stackA first to remove the route, then deploy stackB to add the route. So for some time during the deployment, the `/test` route does not exist.

The recommended way to move a route around is actually similar to what you have described:
1. Create a new route complete, ie. /test2
2. Deploy
3. Change the frontend to call /test2
4. Remove /test
5. Deploy
6. Add /test
7. Deploy
8. Change the frontend to call /test
9. Remove /test2
10. Deploy

I hope this makes sense.

**Comment by justindra** [comment]
Gotcha. Yea that's a really great explanation for that. Thanks @fwang!
