### ISSUE TITLE
sst start: importing files does not work for python

### ISSUE THREAD

**Issue by fwang** [serverless-stack/serverless-stack#535]
The following code works deployed via `sst deploy` but does not work locally via `sst start`.

```python
from hello import world                                                                             

def handler(event, context):                                                                        
 return {                                                                                          
   "statusCode": 200,                                                                              
   "body": world()                                                                                 
 }                                                                                                 
```

```python
def world():
  return "hi"
```

**Comment by bros4president** [comment]
This is because sst runs the python script from the project's root folder and python will lookup the `world` file/module there. In order to import the file you could do something like `import hello from path.to.module.world`, but then this would break the deployment package.

Do you guys have plans to address this or any workaround? Right now we're manually setting local imports while developing and then cleaning the paths before deployment. Not great experience but fortunately we just use Python for some small ML / image processing tasks.

Thanks for this awesome framework by the way. We just finished migrating our whole codebase from Serverless Framework and have 0 regrets :)!

**Comment by fwang** [comment]
Hey @bros4president thanks for hint!

Which version of SST are you using? And Can you share the workaround you are putting in?
