### ISSUE TITLE
Public/private subnets not updated in cdk.context.json

### ISSUE THREAD

**Issue by shechter** [serverless-stack/serverless-stack#556]
Midway through development, I manually converted two public subnets into private subnets in my VPC by deselecting auto-assign IPV4 addresses, and assigning them to new route tables.
When I looked in `cdk.context.json`, the new route tables were reflected, but the subnets were still being listed under
```
    "subnetGroups": [
      {
        "name": "Public",
        "type": "Public",
        "subnets": [
 ```
 
 I replaced the entire cdk.context.json file with `{}` and re-ran `npm run start`
 Only then were the two newly private subnets properly placed under:
 
 ```
   "subnetGroups": [
      {
        "name": "Private",
        "type": "Private",
        "subnets": [
          ...
        ]
      }
    ]
```

**Comment by fwang** [comment]
Hey @shechter, I think this is the expected behaviour. `cdk.context.json` is like a cache so CDK doesn't need to look up the subnets on every build. And from reading the doc on this https://docs.aws.amazon.com/cdk/latest/guide/context.html, it seems the end-user is responsible for clearing the cache.

This behaviour isn't ideal, but I can't think of a good workaround to this on top of my head 🤔

**Comment by shechter** [comment]
It was just odd that it pulled the info about the route tables having changed but not that they were now not auto assigned IP addresses (ie public-> private)! No problem closing the ticket.

**Comment by thdxr** [comment]
Hey @shechter going to close this issue for now.  Let us know if you'd like to discuss further
