### ISSUE TITLE
Function: Add ability to bake in env vars at build-time

### ISSUE THREAD

**Issue by iDVB** [serverless-stack/serverless-stack#845]
Lambda@Edge doesn't support env vars, and you want to reduce the amount of SSM calls with edge functions for performance sake. This would be a good alternative.

**Comment by cbravo** [comment]
Actually the above did not work. 
In order to get our environment variables baked into our functions we had to use a custom esbuild plugin and include it as part of [the build process](https://docs.serverless-stack.com/constructs/Function#configure-esbuild-plugins) The drawback to this approach is that we cannot pass `this.stackName` to the plugin for use inside the Lambda@Edge. One possible solution to this would be to allow inline esbuild configuration instead of having to point to an external file so this:
```
const fn = new sst.Function(this, 'lambda', {
      handler: 'src/lambda.handler',
      role: lambdaRole,
      bundle: { esbuildConfig: './esbuild.js' },
    })
 ```
 would become this: 
 ```
 const fn = new sst.Function(this, 'lambda', {
      handler: 'src/lambda.handler',
      role: lambdaRole,
      bundle: { 
          esbuildConfig: {
              plugins: [
                 envPlugin(this.stackName),
              ]
         }
     },
 })
```

I believe to make this possible changes would need to be made [here](https://github.com/serverless-stack/serverless-stack/blob/master/packages/resources/src/util/nodeBuilder.ts#L285)

**Comment by fwang** [comment]
Closing this as support for inline esbuild config is now supported :)
