### ISSUE TITLE
Support Nested Stacks

### ISSUE THREAD

**Issue by dayvough** [serverless-stack/serverless-stack#87]
Been figuring out how to sort my stacks and I saw that CFN supports Stacks and Nested Stacks. Would be nice if Nested Stacks could also be a construct in SST.

As I'm still new to CDK, would also love to hear any reasons why this isn't a good idea compared to just running things in multiple separate stacks on their own. It's just that preferably I'd rather run some stacks together and Nesting makes for good organisation.

**Comment by jayair** [comment]
Yeah internally we try to avoid using Nested Stacks. It slows down deployments a ton. And I think with the pattern in CDK where you can refer to resources across stacks very easily, makes the need for Nested Stacks not as severe.

That said, yeah we'll look at adding direct support for it in SST in the future. For now a work around, is to just make sure you use the [`App.logicalPrefixedName`](https://docs.serverless-stack.com/constructs/App#logicalprefixedname) method to prefix the stack names.

**Comment by dayvough** [comment]
Got it! Thanks for the prompt reply!

**Comment by jayair** [comment]
No worries. Let me leave this open. If there are more folks that want this then we can prioritize supporting this.

**Comment by rltestingdev** [comment]
The problem I am noticing with cross-stack references is that if Stack B relies on Stack A, then updating the dependencies such as exports in stack A is super difficult. Cloudformation / CDK will give you an error saying that it cannot be updated since Stack B uses it.

I think this is inherently a limitation with CDK/Cloudformation though, so I may have to swap over to nested stacks.

**Comment by fwang** [comment]
@rltestingdev I'm not familiar with nested stack. Say if both stack A and B are sub-stacks of the same nested stack. Can you show me an example of how stack B references/imports a value from stack A?

**Comment by rltestingdev** [comment]
@fwang CF Nested stacks won't throw an error whenever updating Stack output's A even if B depends on it. It will update it properly.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/images/cfn-console-nested-stacks.png is a good image to reference. 

For example, creating and sharing a VPC stack will become difficult because if VPC config changes, then outputs that other stacks dependent on the VPC will change as well.
