### ISSUE TITLE
NextJsSite: Possible to allow hardcoded (or looked up) environment variables to NOT have placeholders?

### ISSUE THREAD

**Issue by dkershner6** [serverless-stack/serverless-stack#888]
Is it possible to allow hardcoded (or looked up) environment variables to NOT have placeholders?

I understand fully the reason behind delaying token environment variables, but what about just...strings?

Related to https://github.com/serverless-stack/serverless-stack/issues/882

**Comment by fwang** [comment]
Hey @dkershner6, in v0.46.0 environment value that are constants (ie. harcoded or looked up) won't get replaced by placeholders. So the environment value is available at build time, and can be used in `getStaticProps`.

Does this work for you? And with this, is your workaround in #882 still required?

**Comment by dkershner6** [comment]
That sounds perfect, @fwang , almost like you guys had the exact same idea. It also nullifies the need for #882 , I will close that now.

There is one more use case this applies to besides `getStaticProps`, btw: configuration of items in `_document` or `_app`. Think along the lines of authentication, typically some kind of SDK need variables from the environment before any page can be built.

**Comment by dkershner6** [comment]
Just tried this out on 0.47.2 and it worked exactly as would be expected for both constants and ssm.lookups.

**Comment by gkemp94** [comment]
@dkershner6  & @fwang 

I think I'm having similar issues as mentioned above, but not sure if it's expected or if there are any workarounds (potentially I'm not doing things as expected). 

I'm building something based on the SST guide (except with NextJS). I'm creating using SST an AuthStack, and providing that to NextJSStaticSite to provide authentication. Except when I run `sst deploy` tokens are placed in place of the environmental variables (which I assume are replaced after the rest of the stack has been created). However the NextJS build runs some code in order to generate the static pages (I assume), however this invocation fails due to the tokens not being valid inputs to the `Amplify.configure` call.


Let me know if I'm going about this the incorrect way or if there is something that can be improved on sst. 

Here is the source code I'm working with. 

Source Code: https://github.com/GeorgeKempLLC/cornerstone

**Comment by dkershner6** [comment]
This is not the same issue as above, as even simple strings used to trigger placeholders.

Your placeholder sounds like expected behavior, but there is likely a way to work around it. I use two separate apps for auth and the webapp, and it works that way, but that is likely overkill for what you are trying to achieve.

**Comment by gkemp94** [comment]
Yeah that seems a little counter-intuitive given my goal is a one command deploy, vs two apps that depend on each other. Unless there is an easy way to do that within SST, where Auth is information passed to WebApp which builds after?

**Comment by dkershner6** [comment]
This actually does work in general for webapps, just not Next's build process, and Amplify is about the only library that cares. You may just try only configuring it client-side. 

`if (typeof window !== "undefined")`

**Comment by gkemp94** [comment]
That would prevent it being used server side once deployed though, in `getServerSideProps`, essentially making the app a standard react app.

**Comment by dkershner6** [comment]
For auth, yes, which may or may not matter depending on use case.

**Comment by gkemp94** [comment]
I feel the solution here is to wait until all dependent stacks (and environment variables) are resolved before building NextJS, which also seems logical since that's the behavior that sst-env exhibits (it won't start your local version of NextJS until all the dependent stacks are resolved). I imagine that would be a larger change?

**Comment by dkershner6** [comment]
Probably, this chicken egg problem is pretty common in CDK in general, I almost always solve by separating into a new app.
